_wandb:
    value:
        cli_version: 0.18.6
        m: []
        python_version: 3.10.15
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.10.15
            "5": 0.18.6
            "8":
                - 1
                - 5
            "12": 0.18.6
            "13": linux-x86_64
batch_size:
    value: 48
dropout:
    value: 0.5
epochs:
    value: 1
fc_layer_size:
    value: 128
learning_rate:
    value: 0.01776445373001413
optimizer:
    value: adam
